---
title: "Manuscript Body"
description: "Main body of paper"
date: "`r Sys.Date()`"
output: html_document
---

```{r child="../Child_RMDs/XX_Funs.Rmd", echo=FALSE}
```
```{r child="../Child_RMDs/MS_Tables.Rmd", echo=FALSE}
```
```{r child="../Child_RMDs/MS_Figures.Rmd", echo=FALSE}
```
<!-- Add child RMDs for results content -->

# Introduction

```{r child="../Child_RMDs/MS_Intro_Short.Rmd", echo=FALSE}
```
```{r child="../Child_RMDs/MS_Aims.Rmd", echo=FALSE}
```

<!-- # Methods -->
```{r child="../Child_RMDs/MS_Method.Rmd", echo=FALSE}
```

<!-- # Results -->
```{r child="../Child_RMDs/MS_Results.Rmd", echo=FALSE}
```

# Discussion

```{r child="../Child_RMDs/MS_Discussion.Rmd", echo=FALSE}
```

# Conclusion

```{r child="../Child_RMDs/MS_Conclusion.Rmd", echo=FALSE}
```

## Acknowledgement {-}
The authors would like to acknowledge the contribution of John Gillam who provided advisory input to this research.

## Availability of data and materials {-#availability-of-data-and-materials}
```{r child="../Child_RMDs/MS_Available_Data_And_Resources.Rmd", echo=FALSE}
```

## Ethics approval {-}
```{r child="../Child_RMDs/MS_Ethics.Rmd", echo=FALSE}
```

## Funding {-#funding}
```{r child="../Child_RMDs/MS_Funding.Rmd", echo=FALSE}
```

## Conflict of Interest {-#conflict-of-interest}
```{r child="../Child_RMDs/MS_COI.Rmd", echo=FALSE}
```