---
title: "MS_Discussion"
author: "Author"
date: "`r Sys.Date()`"
output: html_document
---

In this article we described a framework that we developed to help us implement ready4 - a MOSHEM in youth mental health. We outlined framework standards for an accountable, reusable and updatable MOSHEM and described the modelling toolkit we created for applying those standards to the development and use of the ready4 MOSHEM. We also provided an overview of an initial set of MOSHEM modules developed with the framework to implement a utility mapping study. We reviewed the modules, datasets and analyses generated by that study against framework standards. The work we have described has potential implications for the development of the ready4 MOSHEM and for health economic modelling in mental health. A number of issues have more general relevance to health economic modellers and funders of health economic research.

## Implications for implementing ready4
The most direct implication of the development of the ready4 framework is that it makes it feasible for us to implement a MOSHEM in youth mental health. The standards specified by the framework have enabled us to partially automate workflows for developing and applying ready4 through use of the framework's modelling toolkit. We have demonstrated the practical utility of the modelling toolkit by applying it to authoring, documenting and disseminating ready4 module libraries  [@hamilton_matthew_2022_6084467; @hamilton_matthew_2022_6084824; @hamilton_matthew_2022_6116701; @gao_caroline_2022_6130155], datasets [@DVN/HJXYKQ_2021; @DVN/DKDIB0_2021]; analyses [@hamilton_matthew_2022_6129906; @hamilton_matthew_2022_6416330; @hamilton_matthew_p_2022_6321821], reporting templates [@hamilton_matthew_2022_6116385; @matthew_p_hamilton_2022_5976988] and prediction tools  @matthew_p_hamilton_2021_5646669] used in a utility mapping study [@Hamilton2021.07.07.21260129]. The standardised and partially automated workflows used in creating and sharing these artefacts has the potential to generate significant efficiencies as we apply the ready4 framework to undertaking new economic studies. 

We have also been able to demonstrate the interoperability of the initial ready4 modules developed with the modelling toolkit. The program used to implement the utility mapping analysis [@hamilton_matthew_2022_6129906] combines modules from four module libraries ([@hamilton_matthew_2022_6084467; @hamilton_matthew_2022_6084824; @hamilton_matthew_2022_6116701; @gao_caroline_2022_6130155]) and two framework libraries [@ready4use2022; @ready4show2022]. Example literate programs published on the ready4 documentation website [@rfwn2022] use toy data [@DVN/HJXYKQ_2021] to illustrate the potential for ready4 modules to facilitate study replication and transferability. As demonstrated by the checklist we developed (Table \@ref(tab:checktb)), our framework's standards also provide a mechanism for to assess the extent to which the ready4 MOSHEM meets explicit objectives.  

However, having features that facilitate accountability, reuse and updating is not the same as being accountable, reused and updated. If diverse groups of stakeholders do not review model components, suggest improvements and develop alternatives, then little progress is made towards enhancing model legitimacy. Similarly, making code and data publicly available does not guarantee that others will know of the existence of these tools, trust their validity and find them easy to use. Without reuse, errors in model aretefacts are more likely to remain undetected. Even when errors are detected, they still need to be fixed, but maintaining code and data requires ongoing resourcing through a combination of centralised infrastructure and an active open source community.

To progress from a technical capability to behavioural outcomes, both our framework and MOSHEM need further work. Currently all the framework and model module libraries we have developed are available only as "development" releases. An early priority for us is to undertake the additional development, testing and documenting of these libraries so that we can submit production versions of each library to CRAN [@CRAN2022]. Making R libraries available on CRAN is normally a prerequisite for high levels of reuse. 

The transferability claims we make for our existing modules are to date supported only by example programs using toy data. Our future work aims to address this with real world studies that apply modules to different concepts and contexts. Our current work program also aims to create new ready4 modules for modelling help-seeking choice, spatial epidemiology, household populations and primary mental health services that we hope will provide others with more reasons to use ready4 and contribute to its development. To facilitate code contributions by third parties, our libraries for authoring modules [@ready4pack2022: @ready4fun2022; @ready4use2022] require some additional development to make them easier to use by third parties without knowledge of the naming and directory strucuture conventions we use in authoring code.

<!-- Real applications would be better given importance. -->

## Implications for economic modelling in mental health
Open source approaches have been recommended to help develop the mental health modelling field [@RN73] but only one mental health related model (in Alcohol Use Disorder [@Basu2018]) is currently indexed in the Open Source Models Clearinghouse [@OSMC_20xx;@Emerson2019]. We are aware of just one other open source mental health model - a reference model in Major Depressive Disorder - that is currently in development [@IVIMDD2022]. Of the known barriers to adoption of open source models by health economists (including issues like intellectual property and confidentiality [@Pouwels2022; @Wu2019]), our experience suggests that the biggest challenges may be the enormous effort required to first prepare model code and data for public release in formats that facilitate appropriate reuse by third parties and to then maintain and contunually improve potentially large numbers of digital artefacts. 

Automated tools such as those we developed in our modelling toolkit can help reduce the burden associated with some of these tasks. However, we think the current low rates of adoption by health economists of open source approaches [@Emerson2019; @Michalczyk2018; @Feenstra2022] (which in turn facilitate the collaboration that make modular models more attractive) will only change slowly unless there is significant and strategic investments made by research funders. Currently, the incentive structures for health economists do not promote dedicating large quantities of time to enabling peers to reuse their work.

Reducing waste in research is a responsibility of research funders [@chalmers2014increase] and the poor reproducibility [@Jalali2021; @McManus2019; @Bermejo2017], limited reusability [@Emerson2019; @Michalczyk2018; @Feenstra2022] and uncertain validity [@Ghabri2019; @Radeva2020] of health economic models is wasteful. Approximately 4,000 mental health focused economic evaluation reports were produced between 2000 to 2019 [@RN34]. The intellectual asset represented by this literature could be very substantial if many of the models described in these reports could be brought and kept up to date and made available in formats that maximised transferability to diverse decision contexts. We believe that modular and open source approaches would be well suited to accomplishing this goal and that the framework we have developed could act as an early prototype for solving some of the technical challenges of this task. Ideally such a programme of research would be resourced to be sustained over the medium to long term and to engage a diverse network of investigators, contributors and advisers from high, middle and low income countries.

In addition to extracting more value from the existing health economic knowledge base in mental health, there is an opportunity for research funders to shape how future health economic models in mental health are undertaken. Mental health topics accounted for about 268 of 2829 (10%) peer reviewed economic evaluations undertaken during 26 month period in 2012-2014 identified in a previous review [@pitt2016economic]. There is also likely to a substantial annual output of economic research in mental health that focuses on the other 11 domains identified by Wagstaff and Culyer [@wagstaff2012four]. 

Providing adequate levels of funding to support MOSHEMs, fostering skills, supplying infrastructure (t)

<!-- Resilience of open source project needs multiple maintainers -->

Developing networks of modellers working on common health conditions has been recommended as a strategy for improving model validity [@Sampson2019] and some of us are part of a nascent initiate of this type in mental health [@whiteford_bagheri_2022]. Collaboration between teams of health economists can make some complex modelling projects more feasible [@Arnold2010] and the significant deficits in our understanding of the systems in which mental disorders emerge and are treated [@Fried2020] suggest that there are a number of candidate topics in mental health that might benefit from pooling of efforts. The weak theoretical underpinnings for understanding complex mental health systems [@RN2111] may be a place to start. It remains unclear why increased investments in mental health care have yet to discernibly reduce the prevalence and burden of mental disorders[@RN26].  The  literature, and evidence base, regarding how the requirements, characteristics and performance of mental health services are shaped by spatiotemporal context needs to be further developed [@RN42]. There is also a need for better evidence to identify the social determinants of mental disorders most amenable to preventative interventions, and for which population sub-groups such interventions would be most effective [@RN43]. 

<!-- MH Research priorities (WP3 - Research, WP6 - Economic) https://doi.org/10.1016/S2215-0366(15)00332-6 -->
<!-- http://hdl.handle.net/1893/27205--><!-- CONTEXT: Funders should also support methodological work on context, including the development of reporting templates to facilitate accurate, comprehensive and systematic reporting of context, approaches to evidence synthesis that can capture contextual variation adequately and modelling methods that can leverage the accumulating evidence on contextual variation to predict the reach, implementation and effectiveness of promising interventions in new contexts." --

<!-- the framework represents a technical capacity rather than a behavioural outcome.  -->

<!-- (described in more detail on the project documentation website [@rfwn2022])  -->
<!-- Sustained funding -->


 <!-- - One shot at big changes -->
 <!-- - Our analysis - do it in stages, be transparent, continually improve, get help, be flexible (modelling toolkit / monolithic model), have a framework -->
 <!-- A coding framework for OSHEMs developed in the language R includes standardised approaches to directory structure and naming conventions [@Alarid2019]. -->



<!-- Is it desirable for this to become default authoring tool or better to be replication tool. -->

Estimating the potential uptake of these tools is difficult. 
 


<!-- Add ref to NMHSMN in Australia --> Similarly, developing partnerships between modellers and decision-makers across the life-cycle of a modelling project can help ensure models are appropriately conceptualised, implemented and have practical utility as decision aids [@Zabell2021; @SQUIRES2016588].

- Community building (feasibility)
<!-- Open source is more than open access (limited discussion). -->
- Funding contingent directions - replications / transfers

<!-- Diversify skills - move to tools means software engineering, -->
<!-- More collaboration -->
<!-- Role for SIGs -->
<!-- Make grant proposals that give funders the opportunity to fund this work. -->
<!-- Share some code and data at small scale. -->


## Implications for health economists
<!-- Standardized and transferable approaches to health economic modelling have been recommended. [doi:10.1017/S0266462317000666] -->
<!-- As modelling methods have become more sophisticated, some have argued that more complex models are required to adequately explore certain types of public health topics [@SQUIRES2016588].  -->
<!-- Modellers should be faithful to reaity and values of users DOI: 10.1002/asi.23697 -->
<!-- transferability - [https://doi.org/10.1017/S026646232200321X].  -->
Output by health economists [@pitt2016economic; @wagstaff2012four; @munoz2020health]

## Implications for research funders
<!-- Reducing waste in research is responsibility of research funder: https://doi.org/10.1016/S0140-6736(13)62229-1 -->
>

- unreasonable to expect more accountability without more resources

<!-- greater use of these types of models may require adaptation on the part of funders, modellers and decision-makers. T -->

<!-- Link to Wagstaff - Demand forecasting, valuation of health and healthcare, economic evaluation, utility mapping?? -->

<!-- # Motivation -->

<!-- ## Why develop OSHEMs in mental health -->


Major mental health reform programs, <!-- such as those currently being implemented in Victoria, Australia [@VicRC2021],  -->can involve the identification, prioritisation, sequencing, targeting and monitoring of multiple interdependent initiatives. 



The development, validation and updating of more complex mental health economic models implemented over longer time frames may be too onerous a burden for a single modelling team. 


<!-- Decision makers are frequently left to rely on economic analyses that become less valid and relevant each year. A model can grow stale when changes in the real world, whether sudden (e.g. new pandemics) or gradual (e.g. demographic), is not represented by corresponding updates to relevant model features. Even when the system being modelled remains relatively stable, new research findings may potentially invalidate aspects of a model's original conceptualisation and implementation.  -->

<!-- that rarely explores complex dynamic systems  -->
<!-- [PECUNIA] -->

<!-- Computational modelling could play an important role in developing policies to improve population mental health but this may require significant changes in the way mental health modelling projects are funded, conceptualised and implemented.  -->
 <!-- but, as with health economics more generally, OSHEMs remain rare. Greater use of open source approaches could help improve the scope, validity and usefulness of mental health economic models. -->
 
<!-- Repositories such as Zenodo [@Zenodo2013] and Dataverse [@Dataverse2007] provide persistent storage solutions that generate a Digital Object Identifier (DOI) for each unique item. These repositories are a preferable solution for sharing citable code and data than transitory repositories such as corporate websites or GitHub where items can be deleted or relocated at any time [@sseditors2022]. Zenodo includes tools that automate integration with GitHub, which makes it easy for developers to maintain parallel code repositories - one for disseminating the most up to date development code and the other for archiving citable code releases. --> <!-- Developers storing data in a Dataverse installation have access to multiple meta-data fields to document both a data collection and its individual constituent files.  --><!-- In R, code manuals and websites can be created with the aid of tools such as devtools [@devtools2021], sinew [@sinew2022], roxygen2 [@roxygen2021] and pkgdown [@pkgdown2022].  -->
 
<!-- and the use of version control systems. <!-- such as Git [@git20XX].  -->  
 
<!-- Applying a previously published algorithm [@kross2016] to analyse the most comprehensive archive of released R packages [@CRAN2022] finds that `r gpl_pc_dbl`% are distributed under various forms of General Public License (GPL) [@GNUGPL2022], a copyleft license. -->
<!-- In R, including a CITATION file in the `inst` directory of a package will enable users of that package to retrieve citation information by running a command of the format `citation("Package Name")` in the R console [@Salmon2021]. More generally, including a CITATION.cff file at the top level of your code repository will enable GitHub and Zenodo repositories hosting that item to include the relevant information in their citation tools [@Druskat_Citation_File_Format_2021]. Datasets hosted on Dataverse installations have metadata fields that, once completed by authors, generate citation files for dataset viewers. -->

<!-- A key challenge to generalising health economic models is that they are typically developed to inform a decision problem with a highly specific jurisdictional context. However, a number of choices about how these models are implemented can significantly increase the re-usability of model code in other contexts.  -->
<!-- For example, when generalising a model developed for the Australian context to a UK context, one could create a class that initially inherits all of the methods defined for the Australian model and then write new or replacement methods as needed for the UK model.  -->

<!-- A number of tools and approaches can make the process of implementing and curating changes to model code and data more coherent and efficient.   <!-- Repositories such as Zenodo [@Zenodo2013] and Dataverse [@Dataverse2007] provide persistent access to all published versions of a dataset, each uniquely identifiable. For code, use of version control tools like Git [@git20XX] can ensure that the entire development history of a project is organised so that each version is distinguishable and retrievable by developers. The online platform GitHub [@github2007] can make this version history accessible to anyone. -->

<!-- For R code, the usethis [@usethis2021] package can be used to partially automate version number increments using the convention Major.Minor.Patch.Development (e.g. ExampleSoftware v1.1.1.1). Datasets stored on the Harvard Dataverse use the simpler Major.Minor convention.  -->
<!-- MOSHEMs developed in R can take advantage of templates provided by devtools [@devtools2021] and pkgdown [@pkgdown2022] to run continuous integration checks on GitHub.  --><!-- These tests can include those of units (do individual functions produce expected output?), documentation (does documentation render correctly?; can all example workflows be executed?) and installation (can the software be successfully deployed on multiple types of operating system?).  -->
<!-- MH systems design is not a pharma led project - less concerns about commercial ownership -->

<!-- and for mental health specifically [@Occhipinti2021],  -->
<!-- could provide greater insight about inter-dependencies between candidate policies and the dynamic nature of the mental health systems planning context. Dynamic systems methods might provide the foundations for developing   -->
<!-- and models designed for multiple purposes r -->

 <!-- as part of the Open Value Initiative [@Jansen2019].  -->
 
 <!-- Yet single purpose models that assume static systems may be inadequate for the decision support needs of policymakers and service planners [@PC2020; @Occhipinti2021].  -->
<!-- The large and widespread additional mental health burdens recently observed during the COVID-19 pandemic[@20211700] and predicted as a potential future consequence of climate change [@page_howard_2010], highlight the need to improve the resilience and adaptability of these systems. To help stem growing demand for mental health services, policymakers have also been encouraged to place greater emphasis on tackling the social determinants of mental disorders [@RN11].  -->

<!-- Our approach to model development is to undertake a number of discrete modelling projects of the people, places, platforms and programs that shape the mental health and wellbeing of young people and to progressively link them together by means of a common framework. To model people we are developing synthetic representations of populations of interest [@DVN/HJXYKQ_2021] that describe relevant individual characteristics and their relationships, algorithms that map psychological measures to health utility [@Hamilton2021.07.07.21260129] and choice models for predicting the helpseeking behaviour of young people [@hamilton_matthew_2022_6627995]. Our in-development model of places [@DVN/V3OKZV_2022] has the aim of synthesising geometry and spatial attribute data to characterise the geographic distribution of relevant demographic, environmental, epidemiological and service infrastructure features. We are in the early stages of a multi-annual project to develop a service platform model that will represent the processes and operations of a complex primary youth mental health service. We also plan to extend and update our prior work reviewing economic evidence relating to youth mental health programs [@RN33] so that it can be integrated with this model. Our initial work on **readyforwhatsnext** is focused on Victoria, Australia but the framework we are using to develop it is designed to facilitate extension by ourselves and others to different jurisdictional decision contexts. Progress is reported on a project website [@rfwn2022]. -->