---
title: "MS_Intro_Short"
author: "Author"
date: "`r Sys.Date()`"
output: html_document
---

<!-- `r ifelse(is.na(params$X@background_1L_chr),"",params$X@background_1L_chr)`  -->
Computational models, particularly those addressing economic topics, have become essential tools for health policy development [@dakin2015influence; @Erdemir2020]. Although influential and widely used, health economic models typically have a number of limitations that at best restrict their usefulness and which in some cases may facilitate harmful misuse.

There is a strong case for making health economists more accountable for the appropriate use and social acceptability of their models. Users of models should be able to assess their adequacy for a particular purpose [@thompson2019escape].  This goal is difficult to achieve in the current context of the poor reproducibility [@Jalali2021; @McManus2019; @Bermejo2017] and frequently insufficient validation [@Ghabri2019] of health economic models. Value judgments strongly shape health economic analyses, yet are rarely made explicit, omissions that may lead to socially unacceptable policy recommendations [@duckett2022journey]. A modelling team's value judgments about what questions to address, the most important features of a system to represent and the weighting of different types of evidence may be poorly aligned with those of the people impacted by decisions informed by model analyses [@thompson2022escape]. As health economic models adopt more sophisticated techniques, the need for accountability grows. More complex models may be more prone to propagation errors [@Saltelli2019] and models designed to address multiple questions should be expected to meet more onerous verification and validation obligations [@Eddy2012; @Feenstra2022]. The nature and extent of individual model authorship contributions may be less clear in models implemented over longer time-frames with a large and changing group of collaborators [@thompson2022].

<!-- Many health economic models are released with errors [@Radeva2020]. -->
<!-- As modelling methods have become more sophisticated, some have argued that more complex models are required to adequately explore certain types of public health topics [@SQUIRES2016588].  -->


<!-- Accountability for both the scientific quality and social acceptability of health economic models can be improved.  -->
<!-- Modellers should be faithful to reaity and values of users DOI: 10.1002/asi.23697 -->

Collaborative approaches that encourage re-use of models by other modellers can help make modelling pojects more tractable [@Arnold2010]. However, as many health economic models are owned by pharmaceutical companies and consultancies, commercial considerations can limit the reuse of models and their constituent code and data [@Feenstra2022]. Not all data included in health economic models can be ethically made publicly available due to privacy and confidentiality requirements. Transferring a health economic model developed for one jurisdiction for application in another will involve retaining some features and updating others [@barbieri2010international]. Use of concepts with standardised meanings across jurisdictions [@garcia2021cost], supplying context specific data as replaceable data-packs and distributing source code under licenses that allow derivative works are all steps that can enhance model transferability.
<!-- [https://doi.org/10.1017/S026646232200321X].  -->

Health economic models should be updated and refined as new evidence emerges and decision contexts change [@Jenkins2021], but this occurs infrequently [@Sampson2017]. Decision makers are frequently left to rely on economic analyses that become less valid and relevant each year. A model can grow stale when changes in the real world, whether sudden (e.g. new pandemics) or gradual (e.g. demographic), is not represented by corresponding updates to relevant model features. Even when the system being modelled remains relatively stable, new research findings may potentially invalidate aspects of a model's original conceptualisation and implementation. Funding for health economic modelling projects rarely extend to provision of medium term support for model updates and improvements. The career trajectories of health economists can also mitigate against adequate maintenance of a model, it being relatively common for model authors to have moved on from the team that owns the model and / or from working on the health condition for which the model was developed.

A potential strategy for improving model accountability, reusability and updatability is to make models both modular and open-source.
<!-- Modularity -->
<!-- Definition, value - Computational biology https://doi.org/10.1371/journal.pcbi.1009513 -->
<!-- reusable, interoperable, trans- parent and able to accommodate updates to both data and algorithms - Ecology DOI: 10.1111/2041-210X.14034 -->
<!-- Brain OS modularity: https://www.frontiersin.org/articles/10.3389/fninf.2022.883223/pdf -->

A modular approach to model building involves models being constructed by combining multiple replaceable sub-models (modules) [@pan2021modular]. When used as model sub-components, modules communicate with other modules but they can be also run independently [@barros2023empowering]. Advantages of modular models include feasibility (large projects are broken into smaller tasks, with each component independently developed and tested) and flexibility (making it easier to selectively replace or update specific parts of a model and to scale up or down the level of granularity) [@pan2021modular]. Modular approaches are currently being used to facilitate the development of complex computational models in disciplines such as biology [@pan2021modular], neuroscience [@frazier2022robust] and ecology [@barros2023empowering]. Although the related and enabling concept of reusable reference models has been recommended in health economics [@Afzali2013], peer reviewed studies describing modular health economic models remain relatively rare, though examples exist in tuberculosis [@Trauer2017] and cardiology [@Urach2013].

<!-- A modular approach that ensures that model code and data are decoupled (stored in different files) can help model developers to restrict access to confidential model data, while providing open access to all other model components. -->

<!-- Standardized and transferable approaches to health economic modelling have been recommended. [doi:10.1017/S0266462317000666] -->
The benefits of modular models can be enhanced if multiple modelling teams have the capacity to contribute and use model modules. To facilitate this, modular models may be implemented as open source projects that grant liberal permissions to access and re-use model source code and data [@pan2021modular; @barros2023empowering; @frazier2022robust]. Although there appears to be in principle support from many health economists for greater use of open source health economic models (OSHEMs)  [@Pouwels2022], actual implementations are rare [@Emerson2019; @Michalczyk2018; @Feenstra2022]. Barriers to adoption of OSHEMs include concerns about intellectual property, confidentiality, model misuse and the resources required to support open source implementations [@Pouwels2022; @Wu2019]. Adherence to good practice guidance is an essential requirement for healthcare modelling [@Erdemir2020], but guidelines for implementing OSHEMs remain scarce, piecemeal and need improving [@Sampson2019]. 

<!-- Open source is more than open access (limited discussion). -->
<!-- Reducing waste in research is responsibility of research funder: https://doi.org/10.1016/S0140-6736(13)62229-1 -->
<!-- MH Research priorities (WP3 - Research, WP6 - Economic) https://doi.org/10.1016/S2215-0366(15)00332-6 -->

<!-- and for mental health specifically [@Occhipinti2021],  -->
<!-- could provide greater insight about inter-dependencies between candidate policies and the dynamic nature of the mental health systems planning context. Dynamic systems methods might provide the foundations for developing   -->
<!-- and models designed for multiple purposes r -->

We plan to develop a modular OSHEM of youth mental health. Open source approaches have been recommended to help develop the mental health modelling field [@RN73] but only one mental health related model (in Alcohol Use Disorder [@Basu2018]) is currently indexed [RECHECK] in the Open Source Models Clearinghouse [@OSMC_20xx;@Emerson2019]. Other than our own work, we are aware of just one open source mental health reference model - in Major Depressive Disorder - that is currently in development [@IVIMDD2022]. 
<!-- that rarely explores complex dynamic systems  -->
<!-- [PECUNIA] -->

<!-- Mental health economic studies predominantly examine the affordability and value for money of individual programs [@RN34]. Yet single purpose models that assume static systems may be inadequate for the decision support needs of policymakers and service planners [@PC2020; @Occhipinti2021].  -->

 <!-- as part of the Open Value Initiative [@Jansen2019].  -->

<!-- Computational modelling could play an important role in developing policies to improve population mental health but this may require significant changes in the way mental health modelling projects are funded, conceptualised and implemented.  -->
 <!-- but, as with health economics more generally, OSHEMs remain rare. Greater use of open source approaches could help improve the scope, validity and usefulness of mental health economic models. -->

<!-- CONTEXT: Funders should also support methodological work on context, including the development of reporting templates to facilitate accurate, comprehensive and systematic reporting of context, approaches to evidence synthesis that can capture contextual variation adequately and modelling methods that can leverage the accumulating evidence on contextual variation to predict the reach, implementation and effectiveness of promising interventions in new contexts." -->

 <!-- http://hdl.handle.net/1893/27205-->