---
title: "MS_Imp_Guidelines"
output: html_document
date: '2022-07-21'
---

<!-- Although we are principally interested in using CHEMs to answer policy questions relating to the mental health of young people in Australia, we want to facilitate CHEM transferability to other jurisdictions.  -->

## Case study: health and its value
We have previously described a study [@Hamilton2021.07.07.21260129] to develop utility mapping models for use in samples of young people presenting to primary mental health services. The ready4 software framework was used in that study to develop CHEM modules, supply those modules with data and implement modelling analyses, creating the following artefacts:

 - development version module libraries for describing and validating youth mental health human record datasets [@hamilton_matthew_2022_6084467], scoring health utility [@hamilton_matthew_2022_6084824], specifying utility mapping models [@hamilton_matthew_2022_6116701] and implementing reproducible utility mapping studies [@gao_caroline_2022_6130155]; 

 - a development version library of functions for finding and using utility mapping models developed with these tools [@matthew_p_hamilton_2021_5646669];
 
 - collections of real data (study input and results [@DVN/DKDIB0_2021]) and toy data (synthetic populations for testing model modules [@DVN/HJXYKQ_2021]); 
 
 - programs for replicating all steps from data ingest to manuscript production [@hamilton_matthew_2022_6129906], applying utility mapping models to new data [@hamilton_matthew_2022_6416330] and generating a synthetic representation of the study dataset [@hamilton_matthew_p_2022_6321821]; and
 
 - subroutines for creating a catalogue of utility mapping models [@hamilton_matthew_2022_6116385] and generating a draft scientific manuscript [@matthew_p_hamilton_2022_5976988] for studies implemented with these modules.

We created a checklist (Table \@ref(tab:checktb)) that we used to subjectively assess these study outputs against <!-- Edit_start -->explicit criteria for assessing transparent, reusable and updatable CHEMs that we have previously developed (add REF) <!-- Edit_end -->. For each criterion, we provided a global assessment of whether it was met using the responses “yes”, “no” or “partial”.  We believe our utility mapping study CHEMs have satisfactorily met five of the six criteria (T1, T2, R1, R2 and U1) and have partially met one criterion (U2). The main shortcomings that we identified when applying the assessment criteria was that we have yet to adequately implement unit testing of the R libraries authored as part of this study. 

## Online services
To track our code coverage, we linked our GitHub organisation to an account we established at codecov [@codecov_2022]. The framework also supports integrations with the open science repositories Zenodo [@Zenodo2013] and Dataverse [@Dataverse2007] that provide persistent storage solutions that generate a Digital Object Identifier (DOI) for each code and data collection.

The third party services that our framework is designed to work with include GitHub, Zenodo, Dataverse,
codecov [@codecov_2022]

We created a GitHub organisation (a collection of code repositories) where source code that we author is stored and version controlled. We configured individual repositories in our GitHub organisation to implement continuous integration. By default, code libraries authored with our framework will use continuous integration to assess compliance with policies specified by the Comprehensive R Archive Network (CRAN) [@CRAN2022]. To track our code coverage, we linked our GitHub organisation to an account we established at codecov [@codecov_2022]. To facilitate the creation and hosting of documentation websites, we enabled GitHub Pages in each repository used for code library development. 

We also created a Zenodo community - a collection of permanent, uniquely identified repositories. We then linked our Zenodo community and GitHub organisation so that every time we specify a version of code in one of our GitHub repositories as a “release”, a copy of that code is automatically created on Zenodo with a DOI. Finally, to manage model datasets, we created a dedicated collection within the Harvard Dataverse installation.

## Documentation website
We used functions from our foundation framework library to partially automate website updates relating to available CHEM modules, datasets and analysis programs. 

\blandscape

```{r, child = child_docs_ls$four, echo=FALSE}
```

\elandscape
