---
title: "MS_Imp_Guidelines"
output: html_document
date: '2022-07-21'
---

To enable us to adopt a development approach to readyforwhatsnext that is consistent with meeting all six TRU criteria, we developed a prototype software framework. The software framework is called ready4. 

## Framework user requirements
We created ready4 with one primary user group in mind - ourselves. The framework user requirements (FURs) for ready4 evolved over six years (2018-2024) as we became aware of new issues that we needed to solve. Currently, these requirements are:

FUR 1) A *template module* for use in CHEM implementations in which modules can: (i) be run as independent models; (ii) safely combined, sharing inputs and outputs with each other without unintended interference; and (iii) be selectively replaced, updated or extended.

FUR 2) A *programming syntax* that promotes simplicity and consistency in how algorithms associated with CHEM modules are described and used in health economic analysis programs.

FUR 3) *Developer tools* that integrate with online software development services to support streamlined workflows for authoring R libaries of CHEM modules that are: (i) created using the template module; (ii) written in a consistent house style; (iii) consistently documented; (iv) licensed for reuse; (v) bundled with citation data specifying authorship, funding source, version number and a Digital Object Identifier (DOI); and (vi) quality assured with publicly available acceptance and unit tests. 

<!-- FUR 4) Integration with online open source software development services to streamline the *authoring, testing, documenting and sharing of CHEM modules*.  -->

FUR 4) *Data management tools* that integrate with online data repository services to streamline the ingesting, labeling and sharing of publicly available and confidential data.

FUR 5) *Reporting tools* that: (i) help author reporting template programs that render documents in HTML, Adobe PDF and Microsoft Word file formats; (ii) retrieve version specific reporting template programs from online code repositories and (iii) supply study specific data (e.g authorship details, input data and analysis results) to reporting template programs to render reports and scientific summaries.
<!-- help generate tables for multiple outputs, retrieve templates, modify templates with authorship and results -->

FUR 6) *Search tools* to retrieve web based information on a CHEM project's: (i) publicly available model modules, module libraries and tutorials; (ii) datasets and data collections; and (iii) replication programs and reporting templates.

FUR 7) *Documentation tools* that integrate with open source website development and hosting infrastructure to help: (i) develop a consolidated project documentation website that synthesises content from the individual websites of the project's module libraries, datasets and programs; and (ii) partially automate the updating of website resources such as tutorials and itemised lists of code and data releases. 


## Framework implementation
<!-- The software framework aims to provide a toolkit for: (i) enabling modular implementation of CHEMs; (ii) authoring and documenting CHEM modules; (iii) managing the labelling and transfer of CHEM input and output data; and (iv) authoring reproducible analyses that apply CHEMs to compatible data. -->
We implemented ready4 as R [@RCORE2022] code libraries that integrate with a number of online services. The framework is documented by a project website.

### R libraries 
A library in the R language will typically depend on multiple other R libraries, many of which are likely to have different authors. As the number of third-party dependencies of an R library grows so does the fragility of that library (e.g., the library may cease to work as intended due to changes in one of its dependency libraries). To reduce the fragility of our framework we implemented it as multiple R libraries rather than one R library. In total we authored six novel R libraries to implement the ready4 framework, all of which have distinct purposes and dependencies (Table \@ref(tab:cpkgs)).

One library provides the foundation for the ready4 framework. <!-- In modular model implementations, modules need to be able to share inputs and outputs with each other and to be run as independent models [@barros2023empowering].  -->The ready4 foundation library defines a template CHEM module using R’s S4 class system, that supports an object-oriented programming paradigm. Two notable features of object-oriented programming are encapsulation [@8717448] and inheritence [@8717448]. Encapsulation allows a CHEM module to bundle model data and algorithms in a protected environment, which is useful for helping ensure that CHEM modules continue to work as intended when they are combined<!-- [@ready4oop2022] -->. Inheritence allows new CHEM modules to be created that inherit some or all of the properties of a parent module. Inheritence is useful in cases where it is necessary to update CHEM modules that are being combined to account for interaction effects or to selective edit CHEM modulesbeing transfered to different decision contexts<!-- [@ready4oop2022] -->. The ready4 template CHEM module can be used to create other CHEM modules that inherit a common set of properties (meeting *FUR 1*). One of these inherited properties is a novel syntax of 15 core commands that enable CHEM module algorithms to be consistently named (meeting *FUR 2*). The foundation library also contains tools for retrieving web-based information on CHEM modules, datasets and analysis programs authored with ready4 (meeting *FUR 6*) and tools for developing and maintaining a project documentation website (*FUR 7*).

Three framework module authoring libraries are designed to meet *FUR 3*. <!-- Define functional and object-oriented approaches, acceptance and unit testing. -->The R language supports functional and object-oriented programming paradigms [@10.1214/13-STS452]. Authoring with each of these paradigms is supported by ready4. One module authoring library contains tools for writing functions in a consistent house style and automatically generating basic documentation for each function. A second module authoring library contains tools to help streamline and standardise the authoring of novel, documented CHEM modules from the template CHEM module. A third module authoring library provides tools for disseminating themed bundles of CHEM modules as R libraries that are: documented (with a website and PDF manuals); licensed (using the copyleft GNU GPL-3 [66] by default); easily citable (citation information can be retrieved within an R session or from hosting repositories); and quality assured (each update triggers continuous integration workflows, including any acceptance and unit tests created by module library authors).

A library for managing CHEM data contains tools for supplying CHEM modules with input data ingested from local (i.e., a user's computer) or remote (online repositories) locations, labelling CHEM module datasets and exporting CHEM module data to online repositories (meeting *FUR 4*). A library for authoring reproducible analysis programs and reporting subroutines (*FUR5*) contains tools to help write executables that apply CHEM modules to compatible datasets for the purpose of undertaking health economic analyses. The library supports the creation of analysis programs that are self-documenting (code is integrated with plain English explanations of what it does) and subroutines that can be used as templates that trigger the creation of explanatory documents (e.g., a scientific manuscript).

```{r, child = child_docs_ls$three, echo=FALSE}
```

###	Online services 
Framework libraries are designed to be used in conjunction with a number of third-party online services that users of ready4 will need to establish and configure accounts with. The framework's developer tools integrate with online code development, testing and archiving services. The ready4 framework uses the GitHub [@github2007] service's tools for: software development, testing, version control and distribution; hosting of documentation websites; and transparent record keeping of collaborator contributions. The continuous integration [@CI2017] tools provided by GitHub are used to trigger systematic retesting of module libraries with every edit. <!-- Imported -->These tests can be unit tests (to verify that small, isolated sections of code produce the correct output when run independently) and acceptance tests (to verify that the correct output is produced when multiple code components are run together to perform tasks that meet core user-requirements [@martin2003agile]). A useful concept for informing software users about the extensiveness of testing procedures is code coverage [@ERICWONG2010188] - reports of the proportion of code that has been explicitly tested. The ready4 framework uses the codecov [@codecov_2022] service to measure and share information about code coverage. <!-- End_Imported -->The open science repository service Zenodo [@Zenodo2013] is used to provide persistent storage, uniquely identified with a a Digital Object Identifier (DOI), of each code release. The framework's data management tools use the Dataverse [@Dataverse2007] data repository service for persistent, uniquely identifiable and versioned storage of model input and output data. For the management of frequently updated datasets that do not require persistent storage, ready4 uses GitHub.

###	Documentation website
A project documentation website (https://www.ready4-dev.com) provides guidance to model developers on how to use and contribute improvements to the ready4 software framework. The documentation website is versioned, which means documentation relating to prior versions of framework software can be archived, retrieved and viewed. The documentation website was developed using the Hugo framework [@hugo_2023], Docsy theme [@docsy_2023] and Algolia DocSearch [@algoliadocsearch_2023] and is hosted using the Netlify [@netlify_2023] service. We linked our Netlify account to our GitHub organisation so that the project website would automatically update whenever its source code (publicly available in a GitHub repository) was edited.
