---
title: "MS_Imp_Guidelines"
output: html_document
date: '2022-07-21'
---

We considered literature on modelling practice and reflected on our prior experience with developing and using CHEMs to identify: (i) some core ethical responsibilities of CHEM project teams; (ii) attributes of CHEMs that can suggest fulfillment of these responsibilities; and (iii) criteria against which these attributes can be assessed. 

## Ethical responsibilities of CHEM project teams
<!-- The ethical responsibilities and enabling model attributes we describe have both commonalities and distinctive features compared to a previous  -->
Boden and McKendrick [@10.3389/fpubh.2017.00068] propose a framework for ethical public health modelling based on the criteria of independence (concerning how modeller subjectivity shapes model design), beneficence / non-maleficence (concerning model quality and utility), transparency (concerning the need for policymakers to reliably evaluate model strengths and weaknesses) and justice (concerning the social obligations of modellers to consider and communicate ethical issues about model use). However, these criteria are not specific to the computational model, but are designed to apply to a modelling project as a whole, including a model's conceptual and mathematical representations. The authors propose 13 questions to evaluate ethical risk across the four criteria, but of these, only "is the model code open source or available on request" (for transparency) and "has the model been verified, i.e., does it do what the modeller wants it to do?" (for beneficence / non-maleficence) are specific to model's representation as software. 

To identify ethical issues that are specific to CHEMs, we first considered the distinct phases in a software development project. Software development lifecycle (SDLC) models take different approaches to the inclusion, naming, definition, sequencing and iteration of project phases [@ruparelia2010software]. However, SDLC models typically have components that can principally map to the concepts of *planning* (e.g., identification of system / user requirements and design specifications), *implementation* (e.g., development and testing) and *release* (e.g., deployment, system integration, maintenance and support). For simplicity, we propose one overarching ethical responsibility for CHEM project teams for each phase. These responsibilities are to: 

(i) *establish socially acceptable user requirements and design specifications* (during CHEM planning);

(ii) *ensure fitness for purpose* (of CHEM implementation); and

(iii) *support socially beneficial use* (on CHEM release). 

Transparency underpins all three responsibilities (Table \@ref(tab:timelygls)). Boden and McKendrick’s other ethical criteria can be selectively mapped to each phase's responsibility: justice and independence to the planning responsibility; independence to the implementation responsibility; and beneficence / non-maleficence and justice to the release responsibility. All three ethical responsibilities have implications for both professional practice and project resourcing. As it is unreasonable to place expectations of modellers that they are not resourced to fulfil, these responsibilities should apply jointly to health economic model developers and funders.

<!-- . The authors of that framework propose 13 questions to evaluate ethical risk across the four criteria of  -->
<!-- . However, while our six assessment criteria are specific to three attributes (TRU) of the computational implementation of the model, the prior ethical framework includes questions relevant to the conceptual and mathematical models and the potential impacts of model use. Examples of these more general evaluation questions include (for the justice criterion) “is any lack of knowledge about important parameters attributable to uncertainty or variability?” and (for the beneficence criterion) “if a policy is based on the model evidence, is it more likely to be effective and beneficial than a decision made in the absence of the model?”.  -->

<!-- Multiple ethical considerations of computational modeling have previously been identified [@10.3389/fpubh.2017.00068; @pliakos2021ethics; @thompson2022escape; @calder2018computational],  -->

Misalignment between the values of computational model developers and those of the population groups affected by decisions based on their models presents significant ethical risks [@thompson2022escape; @duckett2022journey].  The value judgments of health economic modellers are rarely adequately specified, omissions that may lead to socially unacceptable policy recommendations [@duckett2022journey]. These value judgments influence the assumptions, selection of model features and standards for evidence that shape health economic model projects [@HARVARD2020112975]. For example, as illustrated in Table \@ref(tab:proscons), project resource constraints may require model developers to make trade-offs when agreeing CHEM *user requirements and design specifications*. These trade-offs in turn determine how straightforward it is for a CHEM to be subsequently amended to reflect alternative value judgments relating to model conceptualisation and mathematical formalisation (Table \@ref(tab:timelygls)).

<!-- For example, to reduce the risk of inequitable policy implementation, it may be important for of a model to predict the benefits of harms of an intervention for different sub-populations [@10.3389/fpubh.2017.00068], but model developers may prefer to allocate a project budget to implementing other model features [@thompson2022escape]. -->

Modellers have duties both to ensure a computational model is *fit for purpose* and to provide potential third-party users with the means of assessing its adequacy for their proposed uses [@Erdemir2020; @Feenstra2022; @thompson2019escape; @10.3389/fpubh.2017.00068]. However, it is common for health economic models to have serious methodological flaws [@carletto_zanuzzi_sammarco_russo_2020; @WONDER2015467]; insufficient validation [@Ghabri2019; @kolovos2017model; @haji2013model], poor reproducibility [@Jalali2021; @McManus2019; @Bermejo2017]; and undeclared errors [@Radeva2020]. Appropriate computational implementation choices can help address many of these shortcomings, for example by automating quality assurance checks and facilitating manual reviews by third parties.

A CHEM will have limited *social benefit* if it is rarely used, if mis-used or when its acceptability and adequacy rapidly decay. Reuse of CHEMs as components of other models can potentially make model development more efficient [@Arnold2010; @garcia2021cost]. However, health economic models face challenges related to transferability across jurisdictions [@garcia2021cost] that create barriers to reuse. Without ongoing maintenance, a CHEM risks becoming less reliable with time [@garcia2021cost] and is at risk of being deployed for purposes for which it is poorly suited [@calder2018computational]. Currently, health economic models are rarely implemented computationally in a manner that facilitates routine updates [@Sampson2017], thus limiting the temporal window within which a CHEM can be validly applied. 
<!-- Reuse of models as components of other models can also make model implementation more efficient [@Arnold2010; @garcia2021cost] but the reusability of models is significantly shaped by computational implementation choices such as how model code and data are authored, documented, licensed and disseminated.  -->

<!-- Common barriers to model re-use include commercial and legal considerations [@Feenstra2022; @Pouwels2022], as well as challenges related to model transferability across jurisdictions [@garcia2021cost]. -->

## CHEM attributes associated with ethical modelling practice
The responsibilities of model project teams over a CHEM lifecycle are easier to state than to measure.  However, aspects of ethical modelling practice may be inferred from measurable attributes of CHEMs. As described in Table \@ref(tab:timelygls),  we believe that the creators of transparent, reusable and updatable (TRU) CHEMs are likely to have fulfilled a number of their ethical obligations.  We therefore selected these model attributes to use as the basis for deriving ethical assessment criteria.

```{r, child = child_docs_ls$two, echo=FALSE}
```

Taking steps to make computational models *transparent* is an important part of ethical public health modelling practice [@10.3389/fpubh.2017.00068]. Guidance on transparency in health economic modelling recommend that model code and data should be clearly documented [@Eddy2012]. Notably, the same guidelines, published over ten years ago, do not recommend sharing model code and data. However, more recent healthcare modelling guidance does recommend public dissemination of such artefacts [@Erdemir2020]. Online repository services such as Zenodo [@Zenodo2013] and Dataverse [@Dataverse2007] provide persistent storage solutions that generate a Digital Object Identifier (DOI) for each code and data collection. Ensuring that calculations are correct and consistent with model specifications is an essential part of CHEM quality assurance [@techver2019]. The extensiveness of such verification checks can be reported using the concept of code coverage [@ERICWONG2010188] - the proportion of model code that has been explicitly tested. Tests should ideally combine both unit tests (to verify that small, isolated sections of code produce the correct output when run independently) and acceptance tests (to verify that the correct output is produced when multiple code components are run together to perform tasks that meet core user-requirements [@martin2003agile]). The nature and extent of individual model authorship contributions can become unclear when models are implemented over longer time-frames with a large and changing group of collaborators [@thompson2022escape]. This issue can be addressed by use of online repository services such as GitHub [@github2007], that provide citation tools and can transparently record all individual code contributions to a modelling project over its lifecycle.

A CHEM that is *reusable* also signals ethical modelling practice. Although making a CHEM’s code, data and documentation publicly available is increasingly considered good practice, it is insufficient to enable model re-use.  Key concerns for health economists when considering whether to reuse a model are generalisability (application without adaptation) and transferability (selective reuse and/or modification of model components) [@RN39]. Writing model algorithms as collections of functions (short, self-contained and reusable software routines that each perform a discrete task) is good scientific computing practice [@Wilson_2017] and promotes selective reuse. Computational implementations that store model code and data in distinct files and locations (as opposed to embedding data such as parameter values into source code) are easier to selectively modify. Modular implementations enable models to be constructed from multiple independently reusable and replaceable sub-models (modules) [@pan2021modular]. 
<!-- The programming concept inheritance [@8717448], deployed in object-oriented programming approaches, can facilitate the duplication and selective modification of models.  -->
Granting permissions to others to use, test and adapt models and their components, can be facilitated by two broad categories of open source licenses. Some guidance strongly recommends the use of permissive licensing [@Wilson_2017] that provides users with great flexibility as to the purposes (including commercial) for which content can be re-used. Alternatively, copyleft licenses [@copyleft2022] can be used to require that derivative works created by content users remain open-source. 
<!-- Compared to using commercial modelling software, authoring CHEMs in an open-source language like R [@RCORE2022] makes it easier to -->
<!-- Using open-source development platforms and licenses can aid both generalizability and transferability. -->
<!-- The choices that CHEM developers make about model implementation and licensing will also shape who can use a model and for what purposes.  -->
<!-- are relatively easier to selectively modify. -->

Models should be *updatable* so that they remain valid for longer, evolving as new evidence emerges and the systems being modelled change [@Jenkins2021; @garcia2021cost]. Ensuring that a model is regularly reviewed to identify and implement required improvements is a recommended defence against model validity decay [@calder2018computational]. Sustainable maintenance of open source research software requires both a core development team and an active user community [@info:doi/10.2196/20028]. Online communities can be an efficient means of engaging model users in testing each version of a model, identifying issues and suggesting improvements. Services such as GitHub [@github2007] provide collaborative code development tools [@MERGEL2015464] that help elicit, integrate and reconcile contributions from multiple contributors and to ensure each update is uniquely identifiable and retrievable. It is also important that verification checks are rerun with each model update, a task that can be automated using the software development practice of continuous integration [@CI2017].  The risk of software revisions having unintended consequences for third party users can be mitigated through the use of deprecation conventions [@zhou2016api] that take an informative and staged approach to retiring outdated CHEMs.
<!-- Currently, the core development team for a CHEM will be typically be funded to produce a project end-point deliverable whose specifications are well defined early in the project. For more complex and multi-purpose CHEMs, particularly those designed to be incorporated into decision support systems, it may be better for development teams to adopt Agile Software Development [@beck2001manifesto], an approach that has been recommended for complex public health software projects [@10.3389/fpubh.2022.899874]. An Agile model will be less clearly specified in the initial project plan, but will instead continually develop in response to the requirements and feedback of users, who are provided with an initial, simplified working version of the model at the earliest feasible opportunity. -->

##	Assessment criteria
For each CHEM attribute that suggests ethical CHEM modelling practice, we identified assessment criteria. <!-- that have the potential to be met with the assistance of software frameworks -->

How *transparent* a CHEM is can be assessed against the criteria:

-	*T1*: Software files (executable code, testing procedures and outcomes and non-confidential data) are available in open access repositories.

-	*T2*: It is easy to see who funded, developed and tested each part of the CHEM and to identify the modelling team’s assumptions, judgments and theories about CHEM development and use.

How *reusable* a CHEM is can be assessed against the criteria:

-	*R1*: Programming practices facilitate both generalisability and transferability.

-	*R2*: Licenses restrict only unethical use and allow anyone to ethically reuse model code and non-confidential data, in whole or in part, without charge, and for purposes that include the creation of derivative works.

How *updatable* a CHEM is can be assessed against the criteria:

-	*U1*: Maintenance infrastructure is in place to support version control and collaboration with model users.

-	*U2*: Each new release of a CHEM is systematically retested, with changes implemented to minimise disruptions for existing model users.
