---
# Supported options: 
#   sn-nature:       Style for submissions to Nature Portfolio journals
#   sn-basic:        Basic Springer Nature Reference Style/Chemistry Reference Style
#   sn-mathphys:     Math and Physical Sciences Reference Style
#   sn-aps:          American Physical Society (APS) Reference Style
#   sn-vancouver:    Vancouver Reference Style
#   sn-apa:          APA Reference Style 
#   sn-chicago:      Chicago-based Humanities Reference Style
#   default:         Default

classoptions: 
  - sn-vancouver      
  - Numbered      # Optional: Use numbered references instead of namedate references (only for sn-nature, sn-basic, sn-vancouver, sn-chicago, sn-mathphys or sn-nature)
  # - referee       # Optional: Use double line spacing 
  # - lineno        # Optional: Add line numbers
  # - iicol         # Optional: Double column layour

title: A prototype software framework for transferable computational health economic models and its early application in youth mental health
titlerunning: Framework for transferable computational models

# authors:
#   - name: Matthew P Hamilton
#     email: matthew.hamilton@orygen.org.au
#     address: Orygen, Parkville, Australia
#     correspondence: true
#     equal_contributor: "yes"
#   - name: Caroline X Gao
#     address: Orygen, Parkville, Australia, Centre for Youth Mental Health, University of Melbourne, Parkville, Australia and School of Public Health and Preventive Medicine, Monash University, Clayton, Australia
#     equal_contributor: "yes"
#   - name: Kate M Filia
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Jana M Menssink
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Sonia  Sharmin
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Nic Telford
#     address: headspace National Youth Mental Health Foundation, Melbourne, Australia
#   - name: Helen Herrman
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Ian B Hickie
#     address: Brain and Mind Centre, Youth Mental Health & Technology, Faculty of Medicine & Health, The University of Sydney,  Australia
#   - name: Cathrine  Mihalopoulos
#     address: Deakin Health Economics, Institute for Health Transformation, Deakin University, Geelong,  Australia
#   - name: Debra J Rickwood
#     address: Faculty of Health, University of Canberra, Australia and headspace National Youth Mental Health Foundation, Melbourne, Australia
#   - name: Patrick D McGorry
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Sue M Cotton
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
authors: 
  - firstname: Matthew
    particle: P 
    lastname: Hamilton
    email: matthew.hamilton1@monash.edu
    affiliation: [1,2]
    corresponding: TRUE
  # - prefix: Mr.
    #suffix: III
    #naturename: Poet Laureate
    # degrees: MSc #, PhD
    #equalcont: These authors contributed equally to this work.
    
  - firstname: Caroline
    lastname: Gao
    #     email: caroline.gao@orygen.org.au
    affiliation: [2,3,1]

  - firstname: Glen
    lastname: Wiesner
    #     email: glen.wiesner@heartfoundation.org.au
    affiliation: [4]

  - firstname: Kate  
    particle: M
    lastname: Filia
    #     email: kate.filia@orygen.org.au
    affiliation: [2,3]

  - firstname: Jana
    particle: M
    lastname: Menssink
    #     email: jana.menssink@orygen.org.au
    affiliation: [2,3]

  - firstname: Petra
    lastname: Plencnerova
    #     email: pplencnerova@headspace.org.au
    affiliation: [5]

  - firstname: David  
    particle: G
    lastname: Baker
    #     email: david.baker@orygen.org.au
    affiliation: [2,3]

  - firstname: Patrick 
    particle: D 
    lastname: McGorry
    #     email: pat.mcgorry@orygen.org.au
    affiliation: [2,3]

  - firstname: Alexandra  
    lastname: Parker
    #     email: alex.parker@vu.edu.au
    affiliation: [6,3]

  - firstname: Jonathan  
    lastname: Karnon
    #     email: jonathan.karnon@flinders.edu.au
    affiliation: [7]

  - firstname: Sue
    particle: M
    lastname: Cotton
    #     email: sue.cotton@orygen.org.au
    affiliation: [2,3]
 
  - firstname: Cathrine
    lastname: Mihalopoulos
    #     email: cathy.mihalopoulos@deakin.edu.au
    affiliation: [1]   
    
affiliations:
  - number: 1
    corresponding: TRUE
    info:
      orgdiv: School of Public Health and Preventive Medicine
      orgname: Monash University
    address:
        #street: "553 St Kilda Road"
        city: Melbourne
        #postcode: 3004
        #state: Victoria
        country: Australia
  - number: 2
    corresponding: FALSE
    info:
      orgname: Orygen
    address:
     #   street: "35 Poplar Road"
        city: Parkville
        # postcode: 3052
        #state: Victoria
        country: Australia
  - number: 3
    corresponding: FALSE
    info:
      orgdiv: Centre for Youth Mental Health
      orgname: The University of Melbourne
    address:
     #   street: "35 Poplar Road"
        city: Parkville
        # postcode: 3052
    #   state: Victoria
        country: Australia
  - number: 4
    corresponding: FALSE
    info:
#      orgdiv: XXXXXXXXXXX
      orgname: Heart Foundation      
    address:
     #   street: "2/850 Collins St"
        city: Docklands
        # postcode: 3008
     #   state: Victoria
        country: Australia
  - number: 5
    corresponding: FALSE
    info:
#      orgdiv: XXXXXXXXXXX
      orgname: headspace National Youth Mental Health Foundation   
    address:
    #  #   street: "485 La Trobe St"
        city: Melbourne
    #     postcode: 3000
    #  #   state: Victoria
        country: Australia     
  - number: 6
    corresponding: FALSE
    info:
      orgdiv: Institute for Health and Sport
      orgname: Victoria University 
    address:
    #  #   street: "70/104 Ballarat Rd"
        city: Footscray
    #     postcode: 3011
    #  #   state: Victoria
        country: Australia 
      # 
  - number: 7
    corresponding: FALSE
    info:
#      orgdiv: XXXXXXXXXXX
      orgname: Flinders University   
    address:
    #     # street: "182 Victoria Square"     
        city: Adelaide
    #     postcode: 5000
    #  #   state: South Australia
        country: Australia 
keywords:  
  - adolescence
  - computational models
  - health economics
  - mental disorders
  - open-source models
  - software frameworks   
  
pacs: 
  jel:
    - "C63"
    - "C88"
    - "I10"
  msc:
    - "91-08"

# Sample for unstructured abstract 

params:
  X: NULL

abstract: "`r paste0(readLines('../Header/abstract.txt'),collapse=' ')`"

bibliography: bibliography.bib

header-includes: |
  %% Per the spinger doc, new theorem styles can be included using built in style, 
  %% but it seems the don't work so commented below
  %\theoremstyle{thmstyleone}%
  \newtheorem{theorem}{Theorem}%  meant for continuous numbers
  %%\newtheorem{theorem}{Theorem}[section]% meant for sectionwise numbers
  %% optional argument [theorem] produces theorem numbering sequence instead of independent numbers for Proposition
  \newtheorem{proposition}[theorem]{Proposition}%
  %%\newtheorem{proposition}{Proposition}% to get separate numbers for theorem and proposition etc.

  %% \theoremstyle{thmstyletwo}%
  \theoremstyle{remark}
  \newtheorem{example}{Example}%
  \newtheorem{remark}{Remark}%

  %% \theoremstyle{thmstylethree}%
  \theoremstyle{definition}
  \newtheorem{definition}{Definition}%
  
  \usepackage{float}
  \let\origfigure\figure
  \let\endorigfigure\endfigure
  \renewenvironment{figure}[1][2] {
      \expandafter\origfigure\expandafter[H]
  } {
      \endorigfigure
  }
  \usepackage{lscape}
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  \usepackage[none]{hyphenat}
  \usepackage[export]{adjustbox}
  \usepackage{multirow}
  \usepackage{longtable}
  \usepackage{array}
  \usepackage{wrapfig}
  \usepackage{colortbl}
  \usepackage{booktabs} 
  \usepackage{colortbl}
  \usepackage{pdflscape}
  \usepackage{tabu}
  \usepackage{threeparttable}
  \usepackage[normalem]{ulem}
  \usepackage{threeparttablex}
  \usepackage{makecell}

# output: rticles::springer_article
output: 
  bookdown::pdf_book: 
    base_format: rticles::springer_article
    # includes:
    #   in_header: preamble.tex
    keep_tex: true
    pandoc_args: 
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      out.extra = "")
#library(flextable)# This forces knitr to label all figures.
```


```{r child="../Child_RMDs/All_Content.Rmd", echo=FALSE, warning=FALSE}
```

